export const EDUCATION_LEVEL = [
    { value: 'A.D.N.', key: 'A.D.N.' },
    { value: 'AA', key: 'AA' },
    { value: 'AAS', key: 'AAS' },
    { value: 'ABA', key: 'ABA' },
    { value: 'ADBus', key: 'ADBus' },
    { value: 'ADIT', key: 'ADIT' },
    { value: 'AE ', key: 'AE ' },
    { value: 'AERONAUTICAL ENGINEERING', key: 'AERONAUTICAL ENGINEERING' },
    { value: 'AET', key: 'AET' },
    { value: 'AFA', key: 'AFA' },
    { value: 'ALA', key: 'ALA' },
    { value: 'AS ', key: 'AS ' },
    { value: 'ASSOCIATED DEGREE', key: 'ASSOCIATED DEGREE' },
    { value: 'AVIATION DEGREE', key: 'AVIATION DEGREE' },
    { value: 'B .PHARMA', key: 'B .PHARMA' },
    { value: 'B. ENG', key: 'B. ENG' },
    { value: 'B. PHIL.', key: 'B. PHIL.' },
    { value: 'B.A.', key: 'B.A.' },
    { value: 'B.A.B.ED', key: 'B.A.B.ED' },
    { value: 'B.A.M.S.', key: 'B.A.M.S.' },
    { value: 'B.ARCH', key: 'B.ARCH' },
    { value: 'B.B.A.', key: 'B.B.A.' },
    { value: 'B.C.A.', key: 'B.C.A.' },
    { value: 'B.C.S', key: 'B.C.S' },
    { value: 'B.COM', key: 'B.COM' },
    { value: 'B.D.S', key: 'B.D.S' },
    { value: 'B.DES', key: 'B.DES' },
    { value: 'B.E.', key: 'B.E.' },
    { value: 'B.E. / B.TECH', key: 'B.E. / B.TECH' },
    { value: 'B.ED.', key: 'B.ED.' },
    { value: 'B.F.A.', key: 'B.F.A.' },
    { value: 'B.F.T.', key: 'B.F.T.' },
    { value: 'B.H.M.S', key: 'B.H.M.S' },
    { value: 'B.IT', key: 'B.IT' },
    { value: 'B.L.', key: 'B.L.' },
    { value: 'B.M.M.', key: 'B.M.M.' },
    { value: 'B.PHARMACY', key: 'B.PHARMACY' },
    { value: 'B.PLAN', key: 'B.PLAN' },
    { value: 'B.S. (ENGINEERING)', key: 'B.S. (ENGINEERING)' },
    { value: 'B.S.L', key: 'B.S.L' },
    { value: 'B.S.W.', key: 'B.S.W.' },
    { value: 'B.SC NURSING', key: 'B.SC NURSING' },
    { value: 'B.SC.', key: 'B.SC.' },
    { value: 'B.SC.B.ED', key: 'B.SC.B.ED' },
    { value: 'B.SC.IT / COMPUTER SCIENCE', key: 'B.SC.IT / COMPUTER SCIENCE' },
    { value: 'B.TECH', key: 'B.TECH' },
    { value: 'BA COMPUTER SCIENCE', key: 'BA COMPUTER SCIENCE' },
    { value: 'BATCHELOR', key: 'BATCHELOR' },
    { value: 'BBM', key: 'BBM' },
    { value: 'BELOW 10TH', key: 'BELOW 10TH' },
    { value: 'BFM (FINANCIAL MANAGEMENT)', key: 'BFM (FINANCIAL MANAGEMENT)' },
    { value: 'BGL', key: 'BGL' },
    {
        value: 'BHA / BHM (HOSPITAL ADMINISTRATION)',
        key: 'BHA / BHM (HOSPITAL ADMINISTRATION)',
    },
    { value: 'BHM (HOTEL MANAGEMENT)', key: 'BHM (HOTEL MANAGEMENT)' },
    { value: 'BHMS', key: 'BHMS' },
    { value: 'BJMC', key: 'BJMC' },
    { value: 'BL / LLB', key: 'BL / LLB' },
    { value: 'BLIS', key: 'BLIS' },
    { value: 'BPHARMA', key: 'BPHARMA' },
    { value: 'BPT', key: 'BPT' },
    { value: 'BSMS', key: 'BSMS' },
    { value: 'BSN /BScN', key: 'BSN /BScN' },
    { value: 'BUMS', key: 'BUMS' },
    { value: 'BVSC', key: 'BVSC' },
    { value: 'C.A.', key: 'C.A.' },
    { value: 'C.S.', key: 'C.S.' },
    {
        value: 'CFA (CHARTERED FINANCIAL ANALYST)',
        key: 'CFA (CHARTERED FINANCIAL ANALYST)',
    },
    { value: 'D.ARCH', key: 'D.ARCH' },
    { value: 'D.ED', key: 'D.ED' },
    { value: 'D.M.L.T', key: 'D.M.L.T' },
    { value: 'D.PHARMACY', key: 'D.PHARMACY' },
    {
        value: 'DEEGREE IN HOTEL MANAGEMENT',
        key: 'DEEGREE IN HOTEL MANAGEMENT',
    },
    { value: 'DFA', key: 'DFA' },
    { value: 'DIPLOMA', key: 'DIPLOMA' },
    {
        value: 'DIPLOMA IN HOTEL MANAGEMENT',
        key: 'DIPLOMA IN HOTEL MANAGEMENT',
    },
    { value: 'DM', key: 'DM' },
    { value: 'DNB', key: 'DNB' },
    { value: 'DOCTORATE', key: 'DOCTORATE' },
    { value: 'ENGINEERING DEPLOMA', key: 'ENGINEERING DEPLOMA' },
    { value: 'F.Y.B.COM', key: 'F.Y.B.COM' },
    { value: 'F.Y.B.SC', key: 'F.Y.B.SC' },
    { value: 'F.Y.BA', key: 'F.Y.BA' },
    {
        value: 'FELLOW OF NATIONAL BOARD (FNB)',
        key: 'FELLOW OF NATIONAL BOARD (FNB)',
    },
    { value: 'G.D.C.& A', key: 'G.D.C.& A' },
    { value: 'H.S.C / 12TH', key: 'H.S.C / 12TH' },
    { value: 'HONOURS DEGREE', key: 'HONOURS DEGREE' },
    { value: 'IAS', key: 'IAS' },
    { value: 'ICWA', key: 'ICWA' },
    { value: 'IES', key: 'IES' },
    { value: 'IFS', key: 'IFS' },
    { value: 'IPS', key: 'IPS' },
    { value: 'IRS', key: 'IRS' },
    { value: 'IT Deploma', key: 'IT Deploma' },
    { value: 'L.D.C.', key: 'L.D.C.' },
    { value: 'L.L.B', key: 'L.L.B' },
    { value: 'L.L.M', key: 'L.L.M' },
    { value: 'M.A.', key: 'M.A.' },
    { value: 'M.A.B.ED', key: 'M.A.B.ED' },
    { value: 'M.A.D.ED', key: 'M.A.D.ED' },
    { value: 'M.ARCH', key: 'M.ARCH' },
    { value: 'M.B.A', key: 'M.B.A' },
    { value: 'M.B.B.S', key: 'M.B.B.S' },
    { value: 'M.C.A', key: 'M.C.A' },
    { value: 'M.C.S', key: 'M.C.S' },
    { value: 'M.COM', key: 'M.COM' },
    { value: 'M.D.', key: 'M.D.' },
    { value: 'M.DES', key: 'M.DES' },
    { value: 'M.E.', key: 'M.E.' },
    { value: 'M.E. / M.TECH', key: 'M.E. / M.TECH' },
    { value: 'M.ED', key: 'M.ED' },
    { value: 'M.ENG', key: 'M.ENG' },
    { value: 'M.L.', key: 'M.L.' },
    { value: 'M.PHARM', key: 'M.PHARM' },
    { value: 'M.PHARMACY', key: 'M.PHARMACY' },
    { value: 'M.PHIL.', key: 'M.PHIL.' },
    { value: 'M.S. (ENGG)', key: 'M.S. (ENGG)' },
    {
        value: 'M.S.C. IT / COMPUTER SCIENCE',
        key: 'M.S.C. IT / COMPUTER SCIENCE',
    },
    { value: 'M.S.ENGINEERING', key: 'M.S.ENGINEERING' },
    { value: 'M.S.Medicine', key: 'M.S.Medicine' },
    { value: 'M.SC', key: 'M.SC' },
    { value: 'M.TECH', key: 'M.TECH' },
    { value: 'MASTER', key: 'MASTER' },
    { value: 'MASTER OF SOCIAL WORK', key: 'MASTER OF SOCIAL WORK' },
    { value: 'MCH', key: 'MCH' },
    { value: 'MD /MS (MEDICAL)', key: 'MD /MS (MEDICAL)' },
    { value: 'MDS', key: 'MDS' },
    { value: 'MFA', key: 'MFA' },
    { value: 'MFM (FINANCIAL MANAGEMENT)', key: 'MFM (FINANCIAL MANAGEMENT)' },
    {
        value: 'MHA / MHM (HOTEL ADMINISTRATION)',
        key: 'MHA / MHM (HOTEL ADMINISTRATION)',
    },
    { value: 'MHM (HOTEL MANAGEMENT)', key: 'MHM (HOTEL MANAGEMENT)' },
    {
        value: 'MHRM (HUMAN RESOURCE MANAGEMENT)',
        key: 'MHRM (HUMAN RESOURCE MANAGEMENT)',
    },
    { value: 'MJMC', key: 'MJMC' },
    { value: 'ML / LLM', key: 'ML / LLM' },
    { value: 'MLIS', key: 'MLIS' },
    { value: 'MMed', key: 'MMed' },
    { value: 'MPT', key: 'MPT' },
    { value: 'M.S.W.', key: 'M.S.W.' },
    { value: 'MVSC', key: 'MVSC' },
    { value: 'OTHER', key: 'OTHER' },
    {
        value: 'OTHER BACHELOR DEGREE IN ENGINEERING / COMPUTERS',
        key: 'OTHER BACHELOR DEGREE IN ENGINEERING / COMPUTERS',
    },
    {
        value: 'OTHER BACHELOR DEGREE IN LEGAL',
        key: 'OTHER BACHELOR DEGREE IN LEGAL',
    },
    {
        value: 'OTHER BACHELOR DEGREE IN MEDICINE',
        key: 'OTHER BACHELOR DEGREE IN MEDICINE',
    },
    {
        value: 'OTHER BATCHELOR DEGREE IN ARTS / SCIENCE / COMMERCE',
        key: 'OTHER BATCHELOR DEGREE IN ARTS / SCIENCE / COMMERCE',
    },
    {
        value: 'OTHER BATCHELOR DEGREE IN MANAGEMENT',
        key: 'OTHER BATCHELOR DEGREE IN MANAGEMENT',
    },
    { value: 'OTHER DEGREE IN FINANCE', key: 'OTHER DEGREE IN FINANCE' },
    { value: 'OTHER DEGREE IN SERVICE', key: 'OTHER DEGREE IN SERVICE' },
    { value: 'OTHER DEPLOMA', key: 'OTHER DEPLOMA' },
    {
        value: 'OTHER MASTER DEGREE IN ENGINEERING  / COMPUTERS',
        key: 'OTHER MASTER DEGREE IN ENGINEERING  / COMPUTERS',
    },
    {
        value: 'OTHER MASTER DEGREE IN LEGAL',
        key: 'OTHER MASTER DEGREE IN LEGAL',
    },
    {
        value: 'OTHER MASTER DEGREE IN MANAGEMENT',
        key: 'OTHER MASTER DEGREE IN MANAGEMENT',
    },
    {
        value: 'OTHER MASTER DEGREE IN MEDICINE',
        key: 'OTHER MASTER DEGREE IN MEDICINE',
    },
    { value: 'P.G.D.C.A.', key: 'P.G.D.C.A.' },
    { value: 'PGD Medicine', key: 'PGD Medicine' },
    { value: 'PGDCA', key: 'PGDCA' },
    { value: 'PGDFM', key: 'PGDFM' },
    { value: 'PGDM', key: 'PGDM' },
    { value: 'PGDORM', key: 'PGDORM' },
    { value: 'PHD', key: 'PHD' },
    { value: 'POLYTECHNIC', key: 'POLYTECHNIC' },
    { value: 'POSTDOCTORAL FELLOW', key: 'POSTDOCTORAL FELLOW' },
    { value: 'S.S.C / 10TH', key: 'S.S.C / 10TH' },
    { value: 'S.Y.B.COM', key: 'S.Y.B.COM' },
    { value: 'S.Y.B.SC', key: 'S.Y.B.SC' },
    { value: 'S.Y.BA', key: 'S.Y.BA' },
    { value: 'T.Y.BA', key: 'T.Y.BA' },
    { value: 'TRADE SCHOOL', key: 'TRADE SCHOOL' },
    { value: 'UNDERGRADUATE', key: 'UNDERGRADUATE' },
    { value: 'UNEDUCATED', key: 'UNEDUCATED' },
    { value: 'ANY', key: 'ANY' },
];
