export const NAKASHATRA_VALUE = [
    { value: 'ASHVINI', key: 'ASHVINI' },
    { value: 'BHARANI', key: 'BHARANI' },
    { value: 'KRITTIKA', key: 'KRITTIKA' },
    { value: 'ROHINI', key: 'ROHINI' },
    { value: 'MRIGASHIRSHA', key: 'MRIGASHIRSHA' },
    { value: 'ARDRA', key: 'ARDRA' },
    { value: 'PUNARVASU', key: 'PUNARVASU' },
    { value: 'PUSHYA', key: 'PUSHYA' },
    { value: 'ASHLESHA', key: 'ASHLESHA' },
    { value: 'MEGHA', key: 'MEGHA' },
    { value: 'PURVA PHALGUNI', key: 'PURVA PHALGUNI' },
    { value: 'UTTARA PHALGUNI', key: 'UTTARA PHALGUNI' },
    { value: 'HASTA', key: 'HASTA' },
    { value: 'CHITRA', key: 'CHITRA' },
    { value: 'SWATI', key: 'SWATI' },
    { value: 'VISHAKHA', key: 'VISHAKHA' },
    { value: 'ANURADHA', key: 'ANURADHA' },
    { value: 'JYESHTHA', key: 'JYESHTHA' },
    { value: 'MULA', key: 'MULA' },
    { value: 'PURVA ASHADHA', key: 'PURVA ASHADHA' },
    { value: 'UTTARA ASHADHA', key: 'UTTARA ASHADHA' },
    { value: 'SHRAVANA', key: 'SHRAVANA' },
    { value: 'DHANISHTA', key: 'DHANISHTA' },
    { value: 'SHATABHISHAJ', key: 'SHATABHISHAJ' },
    { value: 'SHATATARAKA', key: 'SHATATARAKA' },
    { value: 'PURVA BHADRAPADA', key: 'PURVA BHADRAPADA' },
    { value: 'UTTARA BHADRAPADA', key: 'UTTARA BHADRAPADA' },
    { value: 'REVATI', key: 'REVATI' },
    { value: 'ABHIJIT', key: 'ABHIJIT' },
    { value: 'OTHER ', key: 'OTHER ' },
    { value: 'DON’T KNOW', key: 'DON’T KNOW' },
];
